# Homework 2: Homework 2: Intro to Python programming for data analysis

Instructions on the [course webpage](https://bengtssonpalme.github.io/MPBIO-BBT045-2024/python_for_data_analysis/homework_python_intro.html)

## Setup
Files needed in the same directory as this notebook:
- S288C_reference_sequence_R64-4-1_20230830.fsa
- saccharomyces_cerevisiae_R64-4-1_20230830.gff
- Y55_JRIF00000000_SGD_cds.fsa

In [1]:
# load modules
import pandas as pd # enables manipulation of dataframes in Python
from Bio import SeqIO # enables manipulation of sequence files
from Bio.SeqUtils import GC # calculate GC content with Biopython

/local/tmp.5733315/ipykernel_1096114/1453496124.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd # enables manipulation of dataframes in Python

## Task 1: How many genes are on yeast S288C chromosome II?
Read in the file saccharomyces_cerevisiae_R64-4-1_20230830.gff.

Count the number of genes on chromosome II using dataframe filtering and manipulation functions like you've seen in the tutorial. Please have your code produce a numerical result.

In [2]:
# Define the filename and the column names
filename = "saccharomyces_cerevisiae_R64-4-1_20230830.gff"
col_names = ["chromosome", "source", "feature", "start", "end", "score", "strand", "phase", "attributes"]

# Lenght of the FASTA at the end of the file
length_FASTA = 180335-28343

# Read in the gff file, skipping the first 21 rows (info) and the last 151992 rows (FASTA)
saccharomyces_cerevisiae_df = pd.read_csv(filename, sep = '\t', names = col_names, skiprows = 21, skipfooter = length_FASTA, engine = 'python')

# Filter every line which has chromosome set to chrII
ChrII = saccharomyces_cerevisiae_df.loc[saccharomyces_cerevisiae_df.chromosome == "chrII"]
# Filter for genes
ChrII_genes = ChrII.loc[ChrII.feature == "gene"]

# Display the number of rows in the dataframe
len(ChrII_genes)

456

## Task 2: Compute average gene length by chromosome in the S288C yeast strain
Using the same dataframe you used in the Task 1, calculate the average gene length per chromosome. Remember to inspect your data, to see what you're working with. Please use the Pandas dataframe manipulation methods we've covered in the tutorial, as much as you can.

In [3]:
# Filter for genes
genes_Saccharomyces = saccharomyces_cerevisiae_df.loc[saccharomyces_cerevisiae_df.feature == "gene"]

# Create a column with the length of the gene
genes_Saccharomyces = genes_Saccharomyces.assign(length=lambda df: df.end-df.start)
# Source `assign`and `lambda` function: pandas cheat sheet https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

# Group by chromosome
grouped_genes_chromosome = genes_Saccharomyces.groupby('chromosome')

# Display the average of the length for each group (chromosome) using `mean` and `round`
round(grouped_genes_chromosome.length.mean(), 2)

chromosome
chrI       1257.40
chrII      1336.69
chrIII     1203.89
chrIV      1341.95
chrIX      1337.31
chrV       1237.86
chrVI      1330.88
chrVII     1342.01
chrVIII    1268.29
chrX       1398.16
chrXI      1420.87
chrXII     1369.62
chrXIII    1370.18
chrXIV     1357.89
chrXV      1318.05
chrXVI     1347.07
chrmt      2572.43
Name: length, dtype: float64

## Task 3: Extract gene IDs from the S288C yeast GFF file and look for some genes

Here's a function that extracts the gene ID from the column "attributes":

In [4]:
def extract_gene_id_from_attributes_s288c(df_name): 
    # this function requires the argument of the GFF dataframe name be given to it
    # it retrieves the IDs in a Pandas series from the attributes column of the GFF file
    # first save the dataframe to a temporary version to work with
    tmp_df = df_name.copy()
    # split the contents of the attributes column into a list using the semicolons as delimiters
    tmp_series = tmp_df.attributes.str.split(";")
    # overwrite the contents of the attributes column into lists instead of strings 
    tmp_df["attributes"] = tmp_series
    # extract the first element of each list into a new series
    tmp_series = tmp_df.attributes.str[0]
    # split that item into a new list and save only the second element to the series
    tmp_series = tmp_series.str.split("=").str[1]
    # the series containing the gene IDs will be returned
    return tmp_series

a. Using the table manipulation functions, create a new column gene_id in the GFF table. You should find clues for how to do this in the last exercise of the tutorial.

In [5]:
# Feels weird to do this to everything and not just the genes, but here is the code for what is asked ¯\_(ツ)_/¯

# Extract the gene IDs using the function provided
gene_IDs = extract_gene_id_from_attributes_s288c(saccharomyces_cerevisiae_df)

# Create a new column called gene_ID and assign the values extracted above to it
saccharomyces_cerevisiae_df['gene_ID'] = gene_IDs

# Display the result (may need to scroll to the right to see the column)
saccharomyces_cerevisiae_df

,chromosome,source,feature,start,end,score,strand,phase,attributes,gene_ID
0,chrI,SGD,chromosome,1,230218,.,.,.,ID=chrI;dbxref=NCBI:BK006935.2;Name=chrI,chrI
1,chrI,SGD,telomere,1,801,.,-,.,ID=TEL01L;Name=TEL01L;Note=Telomeric%20region%...,TEL01L
2,chrI,SGD,X_element,337,801,.,-,.,Parent=TEL01L;Name=TEL01L_X_element,TEL01L
3,chrI,SGD,X_element_combinatorial_repeat,63,336,.,-,.,Parent=TEL01L;Name=TEL01L_X_element_combinator...,TEL01L
4,chrI,SGD,telomeric_repeat,1,62,.,-,.,Parent=TEL01L;Name=TEL01L_telomeric_repeat_1,TEL01L
...,...,...,...,...,...,...,...,...,...,...
28317,chrmt,SGD,noncoding_exon,85295,85777,.,+,.,Parent=YNCQ0027W_ncRNA;Name=YNCQ0027W_noncodin...,YNCQ0027W_ncRNA
28318,chrmt,SGD,ncRNA,85295,85777,.,+,.,ID=YNCQ0027W_ncRNA;Name=YNCQ0027W_ncRNA;Parent...,YNCQ0027W_ncRNA
28319,chrmt,SGD,gene,85554,85709,.,+,.,ID=Q0297;Name=Q0297;Alias=ORF12;Ontology_term=...,Q0297
28320,chrmt,SGD,CDS,85554,85709,.,+,0,Parent=Q0297_mRNA;Name=Q0297_CDS;orf_classific...,Q0297_mRNA
28321,chrmt,SGD,mRNA,85554,85709,.,+,.,ID=Q0297_mRNA;Name=Q0297_mRNA;Parent=Q0297,Q0297_mRNA

b. Write code (using the table manipulation functions) that 
1) checks whether the following gene IDs are present in the table and
2) only prints the chromosomes on which these are found.

Hint: For 1), check out the isin() function though it's not the only way.
- YJR117W
- YKL156C-A
- YOL110W
- YJR104C
- YJL111W
- YXYZZY
- YNOPE

In [6]:
# Create a list of gene IDs to search for
gene_ID_search_list = ["YJR117W", "YKL156C-A", "YOL110W", "YJR104C", "YJL111W", "YXYZZY", "YNOPE"]

# Use `isin()` to search for the values in this list in the gene_ID column created above:
found_geneIDs = saccharomyces_cerevisiae_df[saccharomyces_cerevisiae_df.gene_ID.isin(gene_ID_search_list)]

# Display the columns "chromsome" and "gene_ID"
found_geneIDs[["chromosome", "gene_ID"]]

      chromosome    gene_ID
14282       chrX    YJL111W
15221       chrX    YJR104C
15278       chrX    YJR117W
15770      chrXI  YKL156C-A
23662      chrXV    YOL110W

## Task 4: Find top 5 longest genes in the S288C yeast
Compute gene lengths as before, but this time simply get the highest 5 values.

In [7]:
# From task 2: 
# Filter for genes
genes_Saccharomyces = saccharomyces_cerevisiae_df.loc[saccharomyces_cerevisiae_df.feature == "gene"]

# Create a column with the length of the gene
genes_Saccharomyces = genes_Saccharomyces.assign(length=lambda df: df.end-df.start)
# Source `assign`and `lambda`: pandas cheat sheet https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf


# New:
# Display the n longest (in this case 5) genes, and only display three columns (chr, ID, length)
genes_Saccharomyces.nlargest(5, 'length')[["chromosome", "gene_ID", "length"]]
# Source `nlargest`: pandas cheat sheet https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

      chromosome  gene_ID  length
17649     chrXII  YLR106C   14732
28138      chrmt    Q0045   12883
16693      chrXI  YKR054C   12278
12176    chrVIII  YHR099W   11234
6385       chrIV  YDR457W    9806

## Task 5: Calculations per gene in the Y55 strain

Convert the FASTA file to a dataframe using the DataFrame() function, setting the columns as `gene_info` and sequence:

In [8]:
#%%script false --no-raise-error

# create a Pandas dataframe from the FASTA file
# ref: https://stackoverflow.com/questions/19436789/biopython-seqio-to-pandas-dataframe
# ref: https://stackoverflow.com/questions/69696077/i-want-to-parse-sequences-and-sequence-ids-from-a-fasta-file-and-assign-them-to

input_fasta = "Y55_JRIF00000000_SGD_cds.fsa"

# create two empty lists for the sequence IDs and sequences
id_list = []
sequence_list = []

with open(input_fasta) as fasta_file: 
    # open the file
    for seq_record in SeqIO.parse(fasta_file, 'fasta'):
        # parse the contents of the FASTA file
        # and append the relevant information to the lists
        id_list.append(seq_record.description)
        sequence_list.append(str(seq_record.seq))

# generate a new Pandas dataframe from the two lists
# ref: https://www.geeksforgeeks.org/create-a-pandas-dataframe-from-lists/
genes_y55_df = pd.DataFrame(list(zip(id_list, sequence_list)), columns = ['gene_info', 'sequence'])

Provided function to extract the gene ID from the `gene_info` fields:

In [9]:
# function to extract the gene IDs from the gene_info columns

def extract_gene_id_from_names_y55(gene_info_col):
    # define the function name & set internal argument
    return gene_info_col.split("|")[3]
    # split the string into a list using pipes ("|") as the delimiters
    # then take the 4th element in the list (Pythonic index 3)
    # return that value to outside of the function

a. Use the function to add a gene_id column.

In [10]:
# Apply the function provided above to the column gene_info
gene_IDs_Y55 = genes_y55_df.gene_info.apply(extract_gene_id_from_names_y55)

# Add the gene IDs as a new column
genes_y55_df['gene_ID'] = gene_IDs_Y55

# Display it
genes_y55_df

,gene_info,sequence,gene_ID
0,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 1-10...,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...,JRIF01000001.1
1,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 1794...,ATGGGTAGAAGAAAAATTGAAATTGAACCTATCAAAGATGATAGAA...,JRIF01000001.1
2,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 4404...,ATGGGAATATTTCGTTGGAACTATCCAGAGAGTTCTGTCCCCGGCG...,JRIF01000001.1
3,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 5652...,ATGTACCAAAATAATGTATTGAATGCTATTTTGGCTTCTGAAAAAT...,JRIF01000001.1
4,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 7411...,ATGAGTGTATTAAGATCTACATGCCTTTTCTTCCCTCCAAGATCCT...,JRIF01000001.1
...,...,...,...
5325,YNL335W_Y55 gi|696433996|gb|JRIF01000367.1| 55...,ATGTCACAGTACGGATTTGTAAGAGTTCCTAGAGAGGTAGAAAAGG...,JRIF01000367.1
5326,YNL334C_Y55 SNO2 gi|696433996|gb|JRIF01000367....,ATGACAGTAAAGGATAAAAATCAACTAGCTCGATGTGATGCATTGA...,JRIF01000367.1
5327,UNDEF_Y55 gi|696433907|gb|JRIF01000396.1| 1501...,ATGGACGACATTGAAACAGCCAAGAATCTGACGGTAAAAGCACGTA...,JRIF01000396.1
5328,UNDEF_Y55 gi|696433883|gb|JRIF01000403.1| 1372...,ATGCCTTATAAAACAGCTATAGATTGCATAGAAGAGTTAGCTACTC...,JRIF01000403.1
5329,UNDEF_Y55 gi|696433878|gb|JRIF01000404.1| 1256...,ATGTTAAGACAAATCCAAGATAAATTTGGTGGTTCTGTAAAATTAA...,JRIF01000404.1

b. Rare codons are biologically significant. In yeast, the rarest codon (besides stop codons) is CGG (mRNA). So, using dataframe manipulation functions on the resulting dataframe from a., create a column to count the occurrence of GCC (DNA) per gene.

In [18]:
# Dataframe used
genes_y55_df

# The rare codon we are interested in
rare_cod = "CGG"

# search for fish, count the number of items in each row
rare_occurances = genes_y55_df.sequence.str.split(rare_cod).str.len()

# Remove one since if no matches = unsplit = 1 string
rare_occurances = rare_occurances-1

# Add the count as a column
genes_y55_df['count_rare_codon'] = rare_occurances

# Display it
genes_y55_df

# NOTE
# Using the following checks that all lines begin with "ATG", which they do
# sum(genes_y55_df.sequence.str.split("^ATG", regex=True).str.len()-1)

,gene_info,sequence,gene_ID,count_rare_codon
0,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 1-10...,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...,JRIF01000001.1,3
1,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 1794...,ATGGGTAGAAGAAAAATTGAAATTGAACCTATCAAAGATGATAGAA...,JRIF01000001.1,9
2,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 4404...,ATGGGAATATTTCGTTGGAACTATCCAGAGAGTTCTGTCCCCGGCG...,JRIF01000001.1,9
3,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 5652...,ATGTACCAAAATAATGTATTGAATGCTATTTTGGCTTCTGAAAAAT...,JRIF01000001.1,6
4,UNDEF_Y55 gi|696435221|gb|JRIF01000001.1| 7411...,ATGAGTGTATTAAGATCTACATGCCTTTTCTTCCCTCCAAGATCCT...,JRIF01000001.1,6
...,...,...,...,...
5325,YNL335W_Y55 gi|696433996|gb|JRIF01000367.1| 55...,ATGTCACAGTACGGATTTGTAAGAGTTCCTAGAGAGGTAGAAAAGG...,JRIF01000367.1,3
5326,YNL334C_Y55 SNO2 gi|696433996|gb|JRIF01000367....,ATGACAGTAAAGGATAAAAATCAACTAGCTCGATGTGATGCATTGA...,JRIF01000367.1,3
5327,UNDEF_Y55 gi|696433907|gb|JRIF01000396.1| 1501...,ATGGACGACATTGAAACAGCCAAGAATCTGACGGTAAAAGCACGTA...,JRIF01000396.1,7
5328,UNDEF_Y55 gi|696433883|gb|JRIF01000403.1| 1372...,ATGCCTTATAAAACAGCTATAGATTGCATAGAAGAGTTAGCTACTC...,JRIF01000403.1,2
5329,UNDEF_Y55 gi|696433878|gb|JRIF01000404.1| 1256...,ATGTTAAGACAAATCCAAGATAAATTTGGTGGTTCTGTAAAATTAA...,JRIF01000404.1,0

## Task 6: Search for a motif in all genes
Filter the S288C_reference_sequence_R64-4-1_20230830.fsa file for those genes that contain the sequence motif "CCACACCACACCCAC".

Which chromosome has the most hits?

Write the code solution using dataframe manipulation functions. Your code should produce only the chromosome number with the highest motif count.

### Setup:

In [12]:
input_fasta = "S288C_reference_sequence_R64-4-1_20230830.fsa"
motif = "CCACACCACACCCAC"

### From Task 5:

Create a Pandas dataframe from the FASTA file

*ref: https://stackoverflow.com/questions/19436789/biopython-seqio-to-pandas-dataframe*

*ref: https://stackoverflow.com/questions/69696077/i-want-to-parse-sequences-and-sequence-ids-from-a-fasta-file-and-assign-them-to*

In [13]:
# create two empty lists for the sequence IDs and sequences
id_list = []
sequence_list = []

with open(input_fasta) as fasta_file: 
    # open the file
    for seq_record in SeqIO.parse(fasta_file, 'fasta'):
        # parse the contents of the FASTA file
        # and append the relevant information to the lists
        id_list.append(seq_record.description)
        sequence_list.append(str(seq_record.seq))

# generate a new Pandas dataframe from the two lists
# ref: https://www.geeksforgeeks.org/create-a-pandas-dataframe-from-lists/
S288C_df = pd.DataFrame(list(zip(id_list, sequence_list)), columns = ['gene_info', 'sequence'])

Also from task 5, but new split pattern to find chromsome number:

In [14]:
# function to extract the gene IDs from the gene_info columns
def extract_gene_id_from_names_S288C(gene_info_col):
    # define the function name & set internal argument
    return gene_info_col.split("] [")[3]
    # split the string into a list using brackets and a space ("] [") as the delimiters
    # then take the 4th element in the list (Pythonic index 3)
    # return that value to outside of the function

### New code:

In [16]:
# Apply the function and remove the trailing bracket
S288C_df['location'] = S288C_df.gene_info.apply(extract_gene_id_from_names_S288C).str.removesuffix("]")

# Split the sequence and remove one, for the same reason as above
S288C_df['counts_motif'] = S288C_df.sequence.str.split(motif).str.len()-1

# Drop irrelevant columns
S288C_df = S288C_df.drop(columns=['gene_info', 'sequence'])

# Display only the row with the highest count using the `idxmax` function from pandas
S288C_df.loc[S288C_df.counts_motif.idxmax(), :]

AttributeError: 'DataFrame' object has no attribute 'gene_info'